[workspace]
members = [
    "crates/pseudocode",
    "crates/pseudocode_cli"
]
package.license = "GPL-3.0-only"
resolver = "3"

[workspace.dependencies]
pseudocode = { path = "crates/pseudocode" }
chumsky = { version = "0.12.0", features = ["pratt"] }
