[workspace]
members = [
    "crates/pseudocode",
    "crates/pseudocode_cli"
]
package.license = "GPL-3.0-only"

[workspace.dependencies]
pseudocode = { path = "crates/pseudocode" }
ariadne = "0.6.0"
chumsky = { version = "0.12.0", features = ["pratt"] }
