[package]
name = "pseudocode_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
pseudocode.workspace = true
ariadne.workspace = true
chumsky.workspace = true
clap = { version = "4.5.54", features = ["derive"] }
