[package]
name = "pseudocode_cli"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
pseudocode.workspace = true
chumsky.workspace = true
ariadne = "0.6.0"
clap = { version = "4.5.54", features = ["derive"] }
